apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo-api
  namespace: pythonapi    
  
  labels:
    app: python-demo-api
    
   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-demo-api
  template:
    metadata:
      
      labels:
        app: python-demo-api     
      

    spec:
      containers:
        - name: python-demo-api
          image: oscka/python-demo-api
          ports:
          - name: http
            containerPort: 8000